---
- hosts: all
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Run the container
      docker_container:
        name: petclinic
        image: pratik141/petclinic:latest
        published_ports: 80:8080
        state: started
